  
image:
  file: .gitpod.Dockerfile

tasks:
  - name: bash
  - command: sudo bash

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: true
    addComment: true

ports:
  - port: 8080
  - port: 2222
    onOpen: ignore
